
==== Nodes

To control which nodes are sent to Kafka, and which of their properties you can define node-patterns in the config.

You can chose Labels and properties for inclusion or exclusion, with `+*+` meaning *all*.

Patterns are separated by semicolons `;`.

The basic syntax is:

----
Label{*};Label1{prop1, prop2};Label3{-prop1,-prop2}
----

[cols="1m,3a",opts=header]
|===
| pattern
| meaning

| Label{*}
| all nodes with this label with all their properties go to the related topic

| Label1:Label2
| nodes with these two labels are sent to the related topic

| Label{prop1,prop2}
| the `prop1` and `prop2` of all nodes with this label are sent to the related topic

| Label{-prop1,-prop2}
| in the node with label `Label` properties `prop1` and `prop2` are excluded

|===


==== Relationships

To control which relationships are sent to Kafka, and which of their properties you can define relationships-patterns in the config.

You can chose Type and properties for inclusion or exclusion, with `+*+` meaning *all*.

Patterns are separated by semicolons `;`.

The basic syntax is:

----
KNOWS{*};MEET{prop1, prop2};ANSWER{-prop1,-prop2}
----

[cols="1m,3a",opts=header]
|===
| pattern
| meaning

| KNOWS{*}
| all relationship with this label with all their properties go to the related topic

| MEET{prop1,prop2}
| the `prop1` and `prop2` of all relationship with this type are sent to the related topic

| ANSWER{-prop1,-prop2}
| in the relationship with type KNOWS properties `prop1` and `prop2` are excluded

|===