= Using with Neo4j Causal Cluster

include::deprecation.adoc[]

ifdef::env-docs[]
[abstract]
--
This chapter describes considerations around using Neo4j Streams with Neo4j Enterprise Causal Cluster.
--
endif::env-docs[]

[[cluster_overview]]
== Overview

link:https://neo4j.com/docs/operations-manual/current/clustering/[Neo4j Clustering] is a feature available in
Enterprise Edition which allows high availability of the database through having multiple database members.

Neo4j Enterprise uses a link:https://neo4j.com/docs/operations-manual/current/clustering/introduction/#causal-clustering-introduction-operational[LEADER/FOLLOWER]
operational view, where writes are always processed by the leader, while reads can be serviced by either followers,
or optionally be read replicas, which maintain a copy of the database and serve to scale out read operations
horizontally.


[[cluster_kafka_connect]]
== Kafka Connect

When using Neo4j Streams in this method with a Neo4j cluster, the most important consideration is to use
a routing driver.  Generally, these are identified by a URI with `neo4j://` as the scheme instead of
just `bolt://` as the scheme.

If your Neo4j cluster is located at `graph.mycompany.com:7687`, simply configure the Kafka Connect worker with

[source]
----
neo4j.server.uri=neo4j://graph.mycompany.com:7687
----

The use of the `neo4j` driver will mean that the Neo4j Driver itself will handle connecting to
the correct cluster member, and managing changes to the cluster membership over time.

For further information on routing drivers, see the link:https://neo4j.com/docs/driver-manual/current/[Neo4j Driver Manual].

[[cluster_remote_clients]]
== Remote Clients

Sometimes there will be remote applications that talk to Neo4j via official drivers, that want to use
streams functionality.  Best practices in these cases are:

* Always use a `neo4j://` driver URI when communicating with the cluster in the client application.
* Use link:https://neo4j.com/docs/driver-manual/current/session-api/configuration/#driver-simple-transaction-fn[Explicit Write Transactions] in
your client application when using procedure calls such as `CALL streams.consume` to ensure that the routing
driver routes the query to the leader.
