[[neo4j_streams_producer_config]]
=== Configuration

You can set the following configuration values in your `neo4j.conf`, here are the defaults.

.neo4j.conf (with default values)
----
kafka.zookeeper.connect=localhost:2181
kafka.bootstrap.servers=localhost:9092
kafka.acks=1
kafka.num.partitions=1
kafka.retries=2
kafka.batch.size=16384
kafka.buffer.memory=33554432
kafka.reindex.batch.size=1000
kafka.session.timeout.ms=15000
kafka.connection.timeout.ms=10000
kafka.replication=1
kafka.linger.ms=1
kafka.transactional.id=
kafka.topic.discovery.polling.interval=300000

streams.source.topic.nodes.<TOPIC_NAME>=<PATTERN>
streams.source.topic.relationships.<TOPIC_NAME>=<PATTERN>
streams.source.topic.nodes.<TOPIC_NAME>.from.<DB_NAME>=<PATTERN>
streams.source.topic.relationships.<TOPIC_NAME>.from.<DB_NAME>=<PATTERN>
streams.source.enabled=<true/false, default=true>
streams.source.enabled.from.<DB_NAME>=<true/false, default=true>
streams.procedures.enabled.from.<DB_NAME>=<true/false, default=true>
streams.source.schema.polling.interval=<MILLIS, the polling interval for getting the schema information>
----

[NOTE]
====
**To use the Kafka transactions please set `kafka.transactional.id` and `kafka.acks` properly**.
Checkout this https://www.confluent.io/blog/transactions-apache-kafka/[blog post] for further details
about transactions in Apache Kafka
====

See the https://kafka.apache.org/documentation/#brokerconfigs[Apache Kafka documentation] for details on these settings.

In case you Kafka broker is configured with `auto.create.topics.enable` to `false`,
all the messages sent to topics that don't exist are discarded;
this because the `KafkaProducer.send()` method blocks the execution, as explained in https://issues.apache.org/jira/browse/KAFKA-3539[KAFKA-3539].
You can tune the custom property `kafka.topic.discovery.polling.interval` in order to
periodically check for new topics into the Kafka cluster so the plugin will be able
to send events to the defined topics.

==== Multi Database Support

Neo4j 4.0 Enterprise has https://neo4j.com/docs/operations-manual/4.0/manage-databases/[multi-tenancy support],
in order to support this feature you can set for each database instance a configuration suffix with the following pattern
`from.<DB_NAME>` to the properties in your neo4j.conf file.

Following the list of new properties that allows to support multi-tenancy:

----
streams.source.topic.nodes.<TOPIC_NAME>.from.<DB_NAME>=<PATTERN>
streams.source.topic.relationships.<TOPIC_NAME>.from.<DB_NAME>=<PATTERN>
streams.source.enabled.from.<DB_NAME>=<true/false, default=true>
----

This means that for each db instance you can specify if:
* use the source connector
* the routing patterns

So if you have a instance name `foo` you can specify a configuration in this way:

----
streams.source.topic.nodes.myTopic.from.foo=<PATTERN>
streams.source.topic.relationships.myTopic.from.foo=<PATTERN>
streams.source.enabled.from.foo=<true/false, default=true>
----

The old properties:

----
streams.source.enabled=<true/false, default=true>
streams.source.topic.nodes.<TOPIC_NAME>=<PATTERN>
streams.source.topic.relationships.<TOPIC_NAME>=<PATTERN>
streams.procedures.enabled=<true/false, default=true>
----

are still valid and they refer to Neo4j's default db instance.

[NOTE]
====
The default database is controlled by Neo4j's *dbms.default_database* configuration property so we're being clear about
which default database applies for this user.
Database names are case-insensitive and normalized to lowercase, and must follow Neo4j database naming rules.
(Reference: https://neo4j.com/docs/operations-manual/current/manage-databases/configuration/#manage-databases-administration)
====

In particular the following property will be used as default value
for non-default db instances, in case of the specific configuration params is not provided:

----
streams.source.enabled=<true/false, default=true>
----

This means that if you have Neo4j with 3 db instances:

* neo4j (default)
* customers
* products

and you want to enable the Source plugin on all instance
you can simply omit any configuration about enabling it, you just need to provide the routing configuration for each instance:

----
streams.source.topic.nodes.loginTopic=Login{userId}
streams.source.topic.nodes.customerTopic.from.customers=Customer{customerId,name,surname}
streams.source.topic.relationships.productTopic.from.products=Products{productId,name}
----

Otherwise if you want to enable the Source plugin only on `customers` and `products` instances
you can do it in this way:

----
streams.source.enabled=false
streams.source.enabled.from.customers=true
streams.source.enabled.from.products=true
streams.source.topic.nodes.loginTopic=Login{userId}
streams.source.topic.nodes.customerTopic.from.customers=Customer{customerId,name,surname}
streams.source.topic.relationships.productTopic.from.products=Products{productId,name}
----
