name: build

on:
  push:
    branches: [ '5.0' ]
  pull_request:
    branches: [ '5.0' ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        neo4j-image: [ "neo4j:4.4", "neo4j:4.4-enterprise", "neo4j:5", "neo4j:5-enterprise", "neo4j:2025", "neo4j:2025-enterprise" ]
    name: Build and test with ${{ matrix.neo4j-image }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd   # v6.0.2

      - name: Set up Java
        uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5.1.0
        with:
          distribution: temurin
          java-version: 11
          cache: 'maven'

      - name: Build and run tests
        env:
          NEO4J_IMAGE: ${{ matrix.neo4j-image }}
        run: mvn -B clean verify --file pom.xml --no-transfer-progress