name: build

on:
  push:
    branches: [ '5.0' ]
  pull_request:
    branches: [ '5.0' ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        neo4j-image: [ "neo4j:4.4", "neo4j:4.4-enterprise", "neo4j:5", "neo4j:5-enterprise", "neo4j:2025", "neo4j:2025-enterprise" ]
    name: Build and test with ${{ matrix.neo4j-image }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0   # v7.0.0

      - name: Set up Java
        uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5.4.0
        with:
          distribution: temurin
          java-version: 11
          cache: 'maven'

      - name: Build and run tests
        env:
          NEO4J_IMAGE: ${{ matrix.neo4j-image }}
        run: mvn -B clean verify --file pom.xml --no-transfer-progress